### ISSUE TITLE
Maven errors using the plugin

### ISSUE THREAD

**Issue by cemeyer2** [ronnyfriedland/adr-maven-plugin#33]
**Describe the bug**

```
Downloading from central: https://repo.maven.apache.org/maven2/de/ronnyfriedland/maven/adr/1.0.1/adr-1.0.1.pom
[WARNING] Failed to retrieve plugin descriptor for de.ronnyfriedland.maven:adr-maven-plugin:1.0.1: Plugin de.ronnyfriedland.maven:adr-maven-plugin:1.0.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for de.ronnyfriedland.maven:adr-maven-plugin:jar:1.0.1
```

Same thing happens with `1.1.0`, cant resolve https://repo.maven.apache.org/maven2/de/ronnyfriedland/maven/adr/1.0.1/adr-1.0.1.pom

Downloading from central: https://repo.maven.apache.org/maven2/de/ronnyfriedland/maven/adr/1.0.1/adr-1.0.1.pom
**To Reproduce**
Configure the plugin in a pom that is not in this git repo. `mvn dependency:resolve` 

```
Downloading from central: https://repo.maven.apache.org/maven2/de/ronnyfriedland/maven/adr/1.0.1/adr-1.0.1.pom
[WARNING] Failed to retrieve plugin descriptor for de.ronnyfriedland.maven:adr-maven-plugin:1.0.1: Plugin de.ronnyfriedland.maven:adr-maven-plugin:1.0.1 or one of its dependencies could not be resolved: Failed to read artifact descriptor for de.ronnyfriedland.maven:adr-maven-plugin:jar:1.0.1
```

**Expected behavior**
The plugin can be imported into my project.

**Comment by ronnyfriedland** [comment]
Can you please provide output of `mvn -U dependency:resolve`. Looks like an issue with plugin prefix resolution.

**Comment by mbarberot** [comment]
Hello, same error here with 1.1.0

Output of `mvn -U dependency-resolve | grep 'adr'` : 

```
Downloading from central: https://repo.maven.apache.org/maven2/de/ronnyfriedland/maven/adr/1.1.0/adr-1.1.0.pom
[WARNING] Failed to retrieve plugin descriptor for de.ronnyfriedland.maven:adr-maven-plugin:1.1.0: Plugin de.ronnyfriedland.maven:adr-maven-plugin:1.1.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for de.ronnyfriedland.maven:adr-maven-plugin:jar:1.1.0
[WARNING] Failed to retrieve plugin descriptor for de.ronnyfriedland.maven:adr-maven-plugin:1.1.0: Plugin de.ronnyfriedland.maven:adr-maven-plugin:1.1.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for de.ronnyfriedland.maven:adr-maven-plugin:jar:1.1.0
```

I can't find the plugin in Maven Central too  : https://mvnrepository.com/search?q=adr%2Dmaven%2Dplugin

**Comment by deathwaiting** [comment]
same problem here 
But the plugin do exist on maven repository.

What doesn't exists is this 

```xml
<parent>
        <groupId>de.ronnyfriedland.maven</groupId>
        <artifactId>adr</artifactId>
        <version>1.1.0</version>
</parent>
```

there is no artifact called `adr` in your maven central repo.

![image](https://github.com/ronnyfriedland/adr-maven-plugin/assets/15851272/ac409847-bf10-43c7-9636-759cdee731b0)

**Comment by ronnyfriedland** [comment]
Thank you for sending some details. I was able to reproduce it now.

**Comment by ronnyfriedland** [comment]
New release 1.1.1 is now staged in nexus repositories and should be available shortly in maven central repo.

Thank you for using my plugin.

**Comment by deathwaiting** [comment]
Thanks for your efforts!

I tested it and it loads and works correctly now into my project.

I had a look into the project before you reply, hoping to build it locally, but I met several issues with running tests.

If you want I do a PR to work on them, but it can be many changes. not sure yet.
